add method to fetch data without decompressing
tilpner/includedir pull request #7
Opened 2018-12-11 20:28 UTC by axos88

We may want to do somthing with the `fn read()` as well

2018-12-13 12:53 UTC, tilpner commented
Why do you want to fetch the data without decompressing it? Maybe there's a better solution than exposing the compressed raw data

2018-12-13 13:12 UTC, tilpner requested changes
Thanks for the PR, should be fine to merge after a few small changes

2018-12-13 13:12 UTC, tilpner commented on lib/src/lib.rs
> +            return Ok((Compression::None, Cow::Owned(v)));
This doesn't need the trailing semicolon

2018-12-13 13:12 UTC, tilpner commented on lib/src/lib.rs
> +        self.files.get(key.borrow() as &str).map( |(c,d)| (*c, Cow::Owned((*d).into()))).ok_or(Error::new(ErrorKind::NotFound, "Key not found"))
This is way too long. How about:

```
        self.files.get(&*key)
            .map(|&(c, d)| (c, Cow::Owned(d.to_owned())))
            .ok_or(Error::new(ErrorKind::NotFound, "Key not found"))
```

2018-12-13 13:12 UTC, tilpner commented on lib/src/lib.rs
> +                let mut r = GzDecoder::new(Cursor::new(compressed));
There is no GzDecoder without flate2. I see you've added a #[cfg] in #8, but it really belongs here.

2018-12-13 21:38 UTC, axos88 commented
rebased on top of the updated #7.
My intentions should be a bit more obvious now.

2018-12-13 21:41 UTC, axos88 commented
The reason for fetching data without decompressing it is... well, because I need the data without decompressing it :)

The goal is to serve the files over http as an asset, and without this change includedir decompresses it, only for the web framework to recompess it when passing it to the browser with (Content-Encoding: gzip).
With this change, I can provide the already compressed data stream directly to the framework to send it to the browser unchanged.

2018-12-14 08:33 UTC, merged

2018-12-14 13:47 UTC, axos88 commented
Thanks 👍